### ISSUE TITLE
[Feature]: Dark/Light mode

### ISSUE THREAD

**Issue by Jagpreet153** [harmeetsingh11/RefactorMate#82] opened 2024-06-21 19:11 UTC
### Description

I would like to add a light/dark mode button for better experience of user

### Justification

Adding a dak /light mode will increase the experience of user in this project 

### Implementation Details (optional)

The feature will be added in the navbar section with a toggle button which will switch between the modes . Kindly assign this issue to me under GSSoC'24

### Screenshots

![Screenshot 2024-06-22 004042](https://github.com/harmeetsingh11/RefactorMate/assets/119691733/af426805-d4d8-457e-8b95-063c9afaaf44)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by harmeetsingh11** [comment] 2024-06-23 17:12
@Jagpreet153 this issue is a duplicate of #61. For this reason, I am closing this issue and assigning you #61.

**Closed** 2024-06-23 17:13 UTC
Labels: enhancement, goal: addition, priority: high
