### ISSUE TITLE
[DOCS]: Pull Request Template Creation

### ISSUE THREAD

**Issue by PradnyaGaitonde** [harmeetsingh11/RefactorMate#52] opened 2024-06-02 17:09 UTC
### Issue Description

I am writing to express my interest in contributing to your repository by creating a pull request template. 
I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests. 
Could you please assign me the issue under gssoc24? I am excited about the opportunity to contribute to your project and help improve the workflow for all contributors.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing [issues](https://github.com/harmeetsingh11/RefactorMate/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/harmeetsingh11/RefactorMate/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/harmeetsingh11/RefactorMate/blob/main/CODE_OF_CONDUCT.md)
- [X] I am willing to work on this issue (optional)

**Comment by harmeetsingh11** [comment] 2024-06-03 18:19
@PradnyaGaitonde the issue is assigned to you. Go ahead!

**Closed** 2024-06-04 14:15 UTC
Labels: documentation, EASY, gssoc, level1
